version: '3'

services:
  cassandra:
    image: cassandra
    container_name: cassandra
    hostname: cassandra-1
    ports:
      - 7000:7000
      - 9042:9042
    networks:
      - cassandra_net
    volumes:
      - cassandra1_data:/var/lib/cassandra:rw
    ulimits:
      nproc: 1024
  
  postgres:
    build:
      context: ./src/postgres
    container_name: postgres
    ports: 
      - 5432:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Aa123456}
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports: 
      - 8080:80
    links: 
      - postgres
    environment: 
      PGADMIN_DEFAULT_EMAIL: phamtanvinh.me@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-Aa123456}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'True'
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10

  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_HOST2:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092,PLAINTEXT_HOST2://192.168.56.106:39092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
    
  connect:
    build: 
      context: ./src/connect
    container_name: connect
    depends_on: 
      - kafka
      - postgres
      - zookeeper
    environment: 
      GROUP_ID: 1
      BOOTSTRAP_SERVERS: kafka:9092
      ADVERTISED_HOST_NAME: connect
      CONFIG_STORAGE_TOPIC: my-connect-configs
      OFFSET_STORAGE_TOPIC: my-offset-configs
      KAFKA_CONNECT_PLUGINS_DIR: /kafka/connect,/kafka/plugins


networks:
  cassandra_net:
    external: true

volumes:
  cassandra1_data:
    external: true
  cassandra2_data:
    external: true
  postgres_data:
    external: true
# docker run -it --rm --network cassandra_net cassandra cqlsh -u cassandra -p cassandra cassandra
# docker run -e DS_LICENSE=accept --network cassandra_net --name dse-studio -p 9091:9091 -d datastax/dse-studio
# docker exec -it --privileged cassandra sh -c 'echo authenticator: PasswordAuthenticator >> /etc/cassandra/cassandra.yaml'
# docker exec -it --privileged cassandra service cassandra restart
# kafka-topics --create --bootstrap-server zookeeper:2181 --replication-factor 1 --partitions 1 --topic test-zk