version: "3"

services:
  zookeeper: 
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    depends_on:
      - broker
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    
  mysql:
    build:
      context: ./mysql
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Aa123456
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
  
  postgres:
    build:
      context: ./postgres
    command: postgres -c config_file=/home/config/postgres.conf
    volumes:
      - ./postgres:/home/config:ro
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: inventory
  
  pgadmin:
    image: dpage/pgadmin4
    ports: 
      - 8080:80
    links: 
      - postgres
    environment: 
      PGADMIN_DEFAULT_EMAIL: phamtanvinh.me@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Aa123456
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'True'
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10  

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.4
    ports:
     - 9200:9200
    environment:
      http.host: '0.0.0.0'
      transport.host: '127.0.0.1'
      xpack.security.enabled: 'false'

  connect:
    build:
      context: ./connect
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - broker
      - mysql
      - postgres
      - es
    environment:
      BOOTSTRAP_SERVERS: broker:9092
      GROUP_ID: 1
      ADVERTISED_HOST_NAME: connect
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offset
      STATUS_STORAGE_TOPIC: my_source_connect_status
      KAFKA_CONNECT_PLUGINS_DIR: /kafka/connect,/kafka/plugins
